version: '3.8'

services:

  redis:
    image: redis:7-alpine
    expose:
      - "6379"

  product-search-service:
    build: ./product-search-service
    expose:
      - "8081"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m"

  cache-service:
    build: ./cache-service
    expose:
      - "8083"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m"

  ai-service:
    build: ./ai-recommendation-service
    expose:
      - "8082"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m"

  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m"