version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          memory: 64M

  product-search-service:
    image: saritab/product-search-service:latest
    container_name: product-search
    expose:
      - "8081"
    environment:
      SERPAPI_KEY: ${SERPAPI_KEY}
      # JVM Heap: 64MB start, 128MB max
      JAVA_OPTS: "-Xms64m -Xmx128m"
    deploy:
      resources:
        limits:
          memory: 200M

  cache-service:
    image: saritab/cache-service:latest
    container_name: cache-service
    expose:
      - "8083"
    environment:
      JAVA_OPTS: "-Xms64m -Xmx128m"
    deploy:
      resources:
        limits:
          memory: 200M

  ai-service:
    image: saritab/ai-recommendation-service:latest
    container_name: ai-service
    expose:
      - "8082"
    environment:
      GIT_HUB_TOKEN: ${GIT_HUB_TOKEN}
      JAVA_OPTS: "-Xms64m -Xmx128m"
    deploy:
      resources:
        limits:
          memory: 200M

  gateway:
    image: saritab/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xms64m -Xmx128m"
    deploy:
      resources:
        limits:
          memory: 200M