server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 50s

      routes:
        - id: product-search-service
          uri: http://product-search-service:8081
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: ai-recommendation-service
          uri: http://ai-service:8082
          predicates:
            - Path=/api/ai/**
          metadata:
            response-timeout: 30s   # in milliseconds
            connect-timeout: 5000
          filters:
            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: aiServiceCB
#                fallbackUri: forward:/fallback/ai

        - id: cache-service
          uri: http://cache-service:8083
          predicates:
            - Path=/api/cache/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always