apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  namespace: microservices
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
        - name: cache-service
          image: saritab/cache-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx192m"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            timeoutSeconds: 3
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 3