apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-search-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-search-service
  template:
    metadata:
      labels:
        app: product-search-service
    spec:
      containers:
        - name: product-search-service
          image: saritab/product-search-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERP_API_KEY
            - name: JAVA_OPTS
              value: "-Xms64m -Xmx192m"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20